import { Inter } from 'next/font/google';
import React from 'react';

import AnimateTransition from './AnimateTransition';
import NavBackground from './components/navBackground';

import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBackground currentPage="home">
          <AnimateTransition>{children}</AnimateTransition>
        </NavBackground>
      </body>
    </html>
  );
}
