import { Inter } from 'next/font/google';
import React from 'react';

import Header from './components/header/Index';

import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <footer className="fixed inset-x-0 bottom-0 flex h-10 items-center justify-center bg-black text-white">
          Footer
        </footer>
      </body>
    </html>
  );
}
